### ISSUE TITLE
week day annotation for other locale

### ISSUE THREAD

**Issue by tkkcc** [marosseleng/compose-material3-datetime-pickers#82] opened 2023-02-16 10:29 UTC
week day annotations are not good for chinese locale
![image](https://user-images.githubusercontent.com/17373509/219339457-de7e69fd-9b21-4379-8568-f3de1bc21607.png)

**Comment by marosseleng** [comment] 2023-02-16 11:34
Hi @tkkcc, thank you for the issue. Can you please explain the nature of the problem?
From my point of view, as a non-speaker, I can see that all of the symbols looks the same, I presume that is the problem.

From the code point of view, there is not much I can do, because to display days abbreviations, the following code is used:
```
DayOfWeek.of(...)
    .getDisplayName(TextStyle.NARROW, locale)
```

It is weird, however, because if I run the same code in Kotlin playgrounds (https://pl.kotl.in/LFI6zQ-tB), it seems to be working fine (for `Locale("zh")`). Producing
```
一
二
三
四
五
六
日
```
.

It seems as if it was a problem in Android implementation of `java.time` package.

To further investigate, can you please provide the following:

1. Version of Android (API level), the app is running at.
2. Device Vendor (due to possible ROM customizations).
3. Exact locale language and region (such as `en_UK`, or `en_US`), preferably from `LocalConfiguration.current`, accessible for instance using
```
/**
 * Returns the preferred [Locale] for user-visible strings.
 */
internal fun Configuration.getDefaultLocale(): Locale {
    return if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {
        locale
    } else {
        if (locales.isEmpty) {
            Locale.getDefault()
        } else {
            locales.get(0)
        }
    } ?: Locale.getDefault()
}
```

Thank you

**Comment by tkkcc** [comment] 2023-02-16 13:34
I confirm it's releated to desugaring. I can reproduce it by
1. Use basic activity template in android studio
2. paste this code in onCreate
```kotlin
val locale = java.util.Locale("zh")
enumValues<java.time.DayOfWeek>()
    .forEach { weekDay ->
        println(weekDay.getDisplayName(java.time.format.TextStyle.NARROW, locale))
    }
```
3. because my minsdk is 24, I apply desugaring method in your readme.
4. run and it print "星", which is not right.

Without desugaring, it will produce corrent result, like in the playground. But I don't know how to support android 7, as jave.time require android 8 api.

I can reproduced it with genymotion android 10 or miui 12.5.

BTW, I tried com.maxkeppeler.sheets-compose-dialogs:calendar, with same desugaring method, it's results are "周一" to "周日", which are recognizable.

**Comment by marosseleng** [comment] 2023-02-16 13:42
What version of desugaring are you using? Can you please check whether the newest version (`v0.6.1` - I released in during today, containing only newer versions) fixes the problem?

In this version, desugaring was upgraded to `2.0.2` in #50, so you might need that version in your app, too. It's weird that it's reproducible on Android 10 as well, as I thought that desugared sources were only used for older versions.

I am not familiar with the library you mention, could you maybe check how they display the abbreviations? It might be possible that they use custom logic to overcome this.

**Comment by tkkcc** [comment] 2023-02-16 14:18
I use desugaring version that you write in readme. Upgrade to 2.0.2 doesn't help. `sheets-compose-dialogs` seems use this api to get weekday names "周一" to "周日"
https://github.com/maxkeppeler/sheets-compose-dialogs/blob/e1d36c69b2b2b33fa59be5501c40849fa0aa6846/calendar/src/main/java/com/maxkeppeler/sheets/calendar/views/CalendarHeaderItemComponent.kt#L50

**Comment by marosseleng** [comment] 2023-02-16 15:35
This, indeed, seems to be an issue with desugared sources.

There is also a threetenbp [issue](https://github.com/ThreeTen/threetenbp/issues/97), which is already [resolved](https://github.com/ThreeTen/threetenbp/pull/135/files).

According to those, similar issue also occur for Japanese and Arabic locales. I will fix those by injecting hardcoded symbols, similarly to the linked PR.

**Comment by marosseleng** [comment] 2023-02-16 16:16
@tkkcc would you mind checking the new PR #84, verifying the symbols are correct?

**Comment by tkkcc** [comment] 2023-02-17 05:35
It's right now. I also suggest detect first weekday based on locale, it's not always sunday.

**Comment by marosseleng** [comment] 2023-02-17 06:53
Thanks for confirmation.

First weekday is already being retrieved from `Locale` as can be seen [here](https://github.com/marosseleng/compose-material3-datetime-pickers/blob/main/datetimepickers/src/main/java/com/marosseleng/compose/material3/datetimepickers/date/ui/DatePicker.kt#L545)

**Closed** 2023-02-17 06:53 UTC
Labels: bug, question, datepicker related

**Comment by darkokoa** [comment] 2023-04-09 09:13
It still happens on my device (locale: `zh-SG`)
![E9F6AD1754F331BB3EFEA9ED0733F366](https://user-images.githubusercontent.com/25176236/230764629-ef5c1ad7-d66c-47e7-a86d-4913d6f3d5df.jpg)

**Comment by darkokoa** [comment] 2023-04-09 09:33
And I want to say that the abbreviations related to the week in Simplified Chinese and Traditional Chinese happen to be the same.

So do not judge the locale as `zh-CN`. Any `language == zh` should apply `zhCnWeekdays`.

**Comment by darkokoa** [comment] 2023-04-09 09:42
> I use desugaring version that you write in readme. Upgrade to 2.0.2 doesn't help. `sheets-compose-dialogs` seems use this api to get weekday names "周一" to "周日" https://github.com/maxkeppeler/sheets-compose-dialogs/blob/e1d36c69b2b2b33fa59be5501c40849fa0aa6846/calendar/src/main/java/com/maxkeppeler/sheets/calendar/views/CalendarHeaderItemComponent.kt#L50

If need to apply this format "周一" to "周日", only need to use `TextStyle.Short` instead of `TextStyle.NARROW` in `language==zh`. 

I have tried using it like this in desugaring and it works.

However, Google calendar apply "一" to "日".
